import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Host_Grotesk,
  Sora,
  Fasthand,
  Plus_Jakarta_Sans,
} from "next/font/google";
import "./globals.css";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

const fasthand = Fasthand({
  weight: "400",
  variable: "--font-fasthand",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const hostGrotesk = Host_Grotesk({
  variable: "--font-host-grotesk",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.variable}  ${geistSans.variable}
    ${geistMono.variable}
    ${hostGrotesk.variable}
    ${sora.variable}
    ${fasthand.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
